# Generated by Django 5.2.4 on 2025-08-09 12:01

import accounts.utils.image_upload
import accounts.utils.nid_upload
import core.utils
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(db_index=True, editable=False, help_text='Unique 9 digit user ID', max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=accounts.utils.image_upload.USER_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('username', models.CharField(db_index=True, help_text='Unique username', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')])),
                ('slug', models.SlugField(editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Unique email address', max_length=60, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(10)])),
                ('number', models.CharField(db_index=True, help_text='Phone number', max_length=20, unique=True)),
                ('payment_number', models.CharField(blank=True, db_index=True, help_text='Payment number (optional)', max_length=20, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='User account balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_name', models.CharField(help_text='First name', max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(help_text='Last name', max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nid_card_number', models.CharField(blank=True, help_text='National ID card number', max_length=20, null=True)),
                ('nid_front_side', models.ImageField(blank=True, help_text='NID front side image', null=True, upload_to=accounts.utils.nid_upload.NID_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('nid_back_side', models.ImageField(blank=True, help_text='NID back side image', null=True, upload_to=accounts.utils.nid_upload.NID_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Address', max_length=80, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('zip_code', models.CharField(blank=True, help_text='ZIP or postal code', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('country', models.CharField(blank=True, help_text='Country', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='user', help_text='User role', max_length=10)),
                ('terms_accept', models.BooleanField(default=False, help_text='Accept terms and conditions')),
                ('is_verify', models.BooleanField(default=False, help_text='Is user verified')),
                ('is_active', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False, help_text='Is user blocked')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
