# Generated by Django 5.2.4 on 2025-08-04 06:03

import accounts.utils.image_upload
import accounts.utils.nid_upload
import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(db_index=True, editable=False, max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.utils.image_upload.USER_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')])),
                ('slug', models.SlugField(editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True, validators=[core.utils.VALIDATE_EMAIL, django.core.validators.MinLengthValidator(10)])),
                ('number', models.CharField(db_index=True, max_length=20, unique=True, validators=[core.utils.VALIDATE_PHONE_NUMBER])),
                ('payment_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[core.utils.VALIDATE_PHONE_NUMBER])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), core.utils.VALIDATE_ALPHA])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), core.utils.VALIDATE_ALPHA])),
                ('nid_front_side', models.ImageField(blank=True, null=True, upload_to=accounts.utils.nid_upload.NID_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('nid_back_side', models.ImageField(blank=True, null=True, upload_to=accounts.utils.nid_upload.NID_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('country', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='user')),
                ('terms_accept', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
