# Generated by Django 5.2.4 on 2025-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number', max_length=20, null=True, unique=True),
        ),
    ]
