# Generated by Django 5.2.4 on 2025-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_added', 'Connection Added'), ('message', 'Message'), ('dispute', 'Dispute'), ('system', 'System')], db_index=True, max_length=50),
        ),
    ]
