################################################################
######### REACT JS DEVELOPMENT DOCKERFILE CONFIGRATION #########
################################################################

# USE OFFICIAL NODE.JS 22 IMAGE
FROM node:22

# SET WORKING DIRECTORY INSIDE THE CONTAINER
WORKDIR /app/frontend

# COPY PACKAGE.JSON AND PACKAGE-LOCK.JSON TO THE WORKING DIRECTORY
COPY package*.json ./

# INSTALL NPM DEPENDENCIES
RUN npm install

# COPY REMAINING APPLICATION FILES
COPY . ./

# EXPOSE PORT 3001
EXPOSE 3001

# START REACT DEVELOPMENT SERVER
CMD ["npm", "run", "dev"]
