# Use official Node.js 20 image
FROM node:20

# Set working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json for caching dependencies
COPY package.json package-lock.json* ./

# Install all dependencies
RUN npm install

# Copy the rest of the application source code
COPY . ./

# Expose port where the dev server will run
EXPOSE 3001

# Start the React development server
CMD ["npm", "run", "dev"]
