version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
    networks:
      - pngnet

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - pngnet

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    networks:
      - pngnet
    depends_on:
      - backend
    command: celery -A app worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pngnet

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - backend
    volumes:
      - ./backend/staticfiles:/backend/staticfiles:ro
      - ./backend/media:/backend/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - pngnet

networks:
  pngnet:
    driver: bridge
