version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
    networks:
      - pngnet
    restart: unless-stopped   # প্রোডাকশনে ভালো হয়, কন্টেইনার ক্র্যাশ করলে আবার চালু হবে

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app  # dev এর জন্য volume; প্রোডাকশনে চাইলে বাদ দিতে পারো, কারণ build এ কোড কপি হয়
    env_file:
      - ./backend/.env
    networks:
      - pngnet
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3  # workers সংখ্যা উল্লেখ করলাম
    restart: unless-stopped

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    networks:
      - pngnet
    depends_on:
      - backend
    command: celery -A app worker --loglevel=info
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pngnet
    restart: unless-stopped

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./backend/staticfiles:/backend/staticfiles:ro
      - ./backend/media:/backend/media:ro     # media ফোল্ডারও readonly করলে ভালো হয়
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - pngnet
    restart: unless-stopped

networks:
  pngnet:
    driver: bridge
