version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
    command: ["/app/entrypoint.sh"]
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3  # or your real DB URL
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:80"   # Frontend served by nginx on port 80 inside container
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/payhourr.com:/etc/letsencrypt/live/payhourr.com:ro
      - /etc/letsencrypt/live/api.payhourr.com:/etc/letsencrypt/live/api.payhourr.com:ro
      - ./backend/staticfiles:/backend/staticfiles:ro
      - ./backend/media:/backend/media:ro
    depends_on:
      - backend
      - frontend
