# Generated by Django 5.2.4 on 2025-08-09 12:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('requirement', models.TextField(blank=True, max_length=5000, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complated', 'Completed'), ('cancle', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_time_extension_requested', models.BooleanField(default=False)),
                ('requested_new_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time_extension_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['delivery_time'], name='orders_orde_deliver_4028ab_idx')],
            },
        ),
    ]
