# Python base image
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app/backend

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    netcat-openbsd \
    libsqlite3-dev \
    && apt-get clean

COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN pip install \
    daphne \
    watchfiles \
    celery \
    django-celery-beat \
    redis

COPY . ./

EXPOSE 8000

CMD ["daphne", "-p", "8000", "-b", "0.0.0.0", "app.asgi:application"]
