# Generated by Django 5.2.4 on 2025-08-04 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='buyer-guide/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_title', models.CharField(blank=True, max_length=280, null=True)),
                ('email', models.EmailField(blank=True, max_length=280, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyRightText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisputePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dispute-policy/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='faq/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_title', models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_number', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='our-mission/')),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='privacy-policy/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='refund-policy/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurePaymentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='secure-payment-process/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller-guide/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='terms-and-conditions/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='terms-of-service/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('short_title', models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatIsPayhourr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='what-is-payhourr/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUsePayhourr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='why-use-payhourr/')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerGuideItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('buyerGuide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.buyerguide')),
            ],
        ),
        migrations.CreateModel(
            name='DisputePolicyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('disputePolicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.disputepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='FaqItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.faq')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('privacyPolicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.privacypolicy')),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('refundPolicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.refundpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='SecurePaymentProcessItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('securePaymentProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.securepaymentprocess')),
            ],
        ),
        migrations.CreateModel(
            name='SellerGuideItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('sellerGuide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.sellerguide')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('termsAndConditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.termsandconditions')),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('termsOfService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.termsofservice')),
            ],
        ),
        migrations.CreateModel(
            name='WhatIsPayhourrItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('what_is_payhourr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.whatispayhourr')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUsePayhourrItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('why_use_payhourr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.whyusepayhourr')),
            ],
        ),
    ]
