# Generated by Django 5.2.4 on 2025-08-09 12:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, help_text='Rating between 0.00 and 5.00', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Rating')),
                ('title', models.CharField(blank=True, help_text='Short title for the review', max_length=100, null=True, verbose_name='Title')),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback about the experience', max_length=2000, null=True, verbose_name='Comment')),
                ('is_anonymous', models.BooleanField(default=False, help_text='If True, reviewer identity will be hidden.', verbose_name='Anonymous Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(help_text='The order this review is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Order')),
                ('reviewee', models.ForeignKey(help_text='The user who is being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewee')),
                ('reviewer', models.ForeignKey(help_text='The user who is giving the review.', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'reviewer'), name='unique_order_reviewer')],
            },
        ),
    ]
