# Generated by Django 5.2.4 on 2025-08-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='receiver_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='sender_number',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='txr_number',
        ),
    ]
