# Generated by Django 5.2.4 on 2025-08-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_receiver_number_deposit_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='number',
            new_name='transaction_id',
        ),
    ]
